### PR TITLE
Relax Parallel Stream Dependency

### PR DESCRIPTION
**Pull request by maennchen**
**This PR addresses**

No issue

**Open questions**
- Could also be changed to `~>  1.0` or `>= 1.0.4 and ~> 1.0`

**Checklist**
- Tests added
- Coverage increases or stays the same
- Docs updated
- Changelog updated

### CODE REVIEW

**Comment by cforcey** [comment]
Thanks so much for proposing this.  Merging this would be great to remove the warning on "coveralls" from the prior version of parallel streams:

https://github.com/beatrichartz/parallel_stream/issues/13

```
warning: found quoted keyword "coveralls" but the quotes are not required. Note that keywords are always atoms, even when quoted. Similar to atoms, keywords made exclusively of ASCII letters, numbers, and underscores do not require quotes
... deps/parallel_stream/mix.exs:17:30
```

**Comment by isfalcantara** [comment]
Sorry to ask, but is there any issue that blocks the merging of this PR @beatrichartz ?

**Comment by beatrichartz** [comment]
Thanks for this, merged. Apologies this took a while.

**Comment by maennchen** [comment]
Thanks @beatrichartz! No worries 😊

**Pull request merged**
